services:    
  localstack:
    container_name: localstack
    hostname: localstack
    image: localstack/localstack:2.0
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DYNAMODB_SHARE_DB=1  
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - REGION=eu-west-2