<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.400.69" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.404.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\elastic_app.application\elastic_app.application.csproj" />
    <ProjectReference Include="..\elastic_app.domain\elastic_app.domain.csproj" />
  </ItemGroup>

</Project>
