name: "CI"
run-name: "Build #${{ github.run_number }} - ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - "bugfix/*"
      - "feature/*"
      - "refactor/*"
      - "main"

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image (Unit Tests)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: unit-tests
          tags: myapp-tests:latest
          load: true
        
        