name: "Terraform CI/CD"
run-name: "Build #${{ github.run_number }}"

on:
  workflow_dispatch:
    inputs:
      # username:
      #   required: true
      #   type: string
      #   description: 'username for go mod init'
      #   default: 'alexplayer15'
      # directory:
      #   required: true
      #   type: string
      #   description: 'directory for go mod init'
      #   default: 'elastic_app_v2'
      terraform_version: 
        required: false
        type: string
        description: 'terraform version to use'
        default: '1.9.5'
      terraform_directory:
        required: false
        type: string 
        description: directory terraform main.tf file is located 
        default: terraform
      destroy_all_resources:
        required: false
        type: boolean
        description: 'check this to destroy all existing resources'
        default: false
      image_tag:
        required: true
        type: string 
        description: image tag to be deployed
  workflow_call:
    inputs:  
      terraform_version: 
        required: false
        type: string
        description: 'terraform version to use'
        default: '1.9.5'
      terraform_directory:
        required: false
        type: string 
        description: directory terraform main.tf file is located 
        default: terraform
      destroy_all_resources:
        required: false
        type: boolean
        description: 'check this to destroy all existing resources'
        default: false  
      image_tag:
        required: true
        type: string 
        description: image tag to be deployed
          
jobs:
  terraform-cicd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraform_directory }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-2' 

    - name: Terraform init
      run: |
        terraform init

    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: '1.23.0' 

    - name: Destroy Terraform 
      if: ${{ inputs.destroy_all_resources }}
      run: |
         terraform destroy --auto-approve

    - name: Terraform validate
      if: ${{ !inputs.destroy_all_resources }}
      run: |
        terraform validate

    # - name: Install Terratest Dependencies
    #   run: |
    #     go mod init github.com/${{ inputs.username }}/${{ inputs.directory }}
    #     go mod tidy

    # - name: Run Terratest
    #   run: |
    #     cd test
    #     go test -v -timeout 30m ./...
        
    - name: Terraform plan 
      if: ${{ !inputs.destroy_all_resources }}
      run: |
        terraform plan -var="image_tag=${{ inputs.image_tag }}" -out=../terraform.plan

    - name: Terraform apply
      if: ${{ !inputs.destroy_all_resources }}
      run: |
        terraform apply -var="image_tag=${{ inputs.image_tag }}" --auto-approve

        